version: '3'

services:
  web:
    build: .
    container_name: api
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c " python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput
             python manage.py runserver 0.0.0.0:8000"
