export const conditions: readonly String[] = [
    "Asthma",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Interstitial Lung Disease (ILD)",
    "Chronic Cough",
    "Pulmonary Hypertension",
    "Sleep Disorders",
    "Meningitis - fungal",
    "Coma - hyperosmolar nonketotic (HONK)",
    "Filtering bleb failed",
    "Cigarette smoker",
    "Mediastinal adenopathy",
    "Seizure - electrographic",
    "Edema peripheral",
    "Cystocele",
    "Hyperhidrosis",
    "Chorioamnionitis",
    "Sexual abuse",
    "Histiocytosis - malignant",
    "Pleuritic pain",
    "Esophageal dysphagia",
    "Glaucoma - low tension",
    "Superficial phlebitis",
    "Laceration",
    "Cruciate ligament tear",
    "Erectile dysfunction",
    "Vision - diminished",
    "Sinus tenderness",
    "Vision - blurred",
    "Muscle rupture",
    "Diabetic nephropathy - juvenile controlled",
    "Whipple's disease",
    "Achalasia",
    "Felty syndrome",
    "Anaphylaxis",
    "Diabetic enteropathy",
    "Uterine hemorrhage",
    "Amniocentesis",
    "Varicella",
    "Diarrhea",
    "Glomerulonephritis - mesangial proliferative",
    "Riedel's thyroiditis",
    "Paget's disease of bone",
    "Nasal polyp",
    "Erythrocytosis",
    "Alkalosis - respiratory",
    "Sturge-Weber syndrome",
    "Ocular herpes zoster",
    "Wound dehiscence",
    "Excoriation - neurotic",
    "Mucormycosis",
    "Renal insufficiency - chronic",
    "Renal artery stenosis",
    "Menorrhagia",
    "Sulfhemoglobinemia",
    "Gastric varices",
    "Adenoidectomy",
    "Heel pain",
    "Dog bite",
    "Lithium toxicity",
    "Anal/rectal surgery",
    "Scleroderma",
    "Spermatogenic arrest",
    "Flatulence",
    "Stab wound",
    "Factor X deficiency",
    "Agoraphobia with panic attacks",
    "Atrophic gastritis",
    "Numbness",
    "Macular degeneration",
    "Tooth loss",
    "Cholesterolosis",
    "Bile stasis",
    "Chlamydia pneumonia",
    "Conjunctival hemorrhage",
    "Osteoma",
    "CMV retinitis",
    "Granuloma - non-necrotizing",
    "Forearm fracture - open",
    "Beta thalassemia",
    "Alopecia areata",
    "Telogen effluvium",
    "Colon polyp",
    "Breast mass",
    "Caf\u00e9 au lait spot",
    "Facial bone fracture",
    "Hyperventilation",
    "Adenosis - sclerosing",
    "Varices",
    "Hidradenitis",
    "Laryngectomy",
    "Nephropathy - urate",
    "Myalgia",
    "Tongue - red",
    "Pharyngeal ulcer",
    "Intraductal carcinoma",
    "Central nervous system shunt",
    "Jaundice",
    "Takayasu's arteritis",
    "Pityriasis alba",
    "Hepatic metastases",
    "Behavior problem",
    "Esotropia",
    "Hemoptysis",
    "Pneumoconiosis",
    "Akathisia",
    "Intraventricular hemorrhage",
    "Hypotonia",
    "Hypotension",
    "Heart disease - congenital",
    "Dysmenorrhea",
    "Splenic infarction",
    "Acidosis - metabolic",
    "Pituitary tumor",
    "Denervation",
    "Hemoglobin A2 - high",
    "Bullous pemphigoid",
    "Coronary artery disease",
    "Hydatidiform mole - invasive",
    "Pseudoxanthoma elasticum",
    "Billroth I gastrectomy",
    "Liposarcoma - myxoid",
    "Vaginal bleeding",
    "Ectropion",
    "Hip dislocation - congenital",
    "Hip subluxation - congenital",
    "Ganglioneuroblastoma",
    "Glomerulonephritis - acute",
    "Cleft lip/pal surgery",
    "Retinoblastoma",
    "Epidermal inclusion cyst",
    "Familial Mediterranean fever",
    "Otorrhea",
    "Atten deficit hyperactivity disorder",
    "Liver transplant",
    "Open heart surgery",
    "Gastric obstruction",
    "Insomnia",
    "Parapsoriasis",
    "Atrial septal defect",
    "Pancreatitis - chronic",
    "Intrauterine device (IUD)",
    "Bioprosthetic heart valve",
    "Erythroblastosis fetalis",
    "Leiomyosarcoma",
    "Brenner tumor - malignant",
    "Pulmonary edema",
    "Osteoarthritis",
    "Verruca plana",
    "Bromhidrosis",
    "Pharyngeal exudates",
    "Spontaneous abortion",
    "Lipogranuloma",
    "Hepatitis - giant cell",
    "Laryngeal abscess",
    "Vertebrobasilar insufficiency",
    "Salivary duct stone",
    "Toe strain",
    "Polyuria",
    "Coma",
    "Suspected child abuse",
    "Hypokalemia",
    "Angina - recurrent",
    "Glaucoma - combined mechanism",
    "Hepatomegaly",
    "AAA repair",
    "Major depression - recurrent",
    "Chorioretinitis",
    "Berry aneurysm",
    "Cutaneous B cell lymphoma",
    "Acropustulosis - infantile",
    "Amyotrophic lateral sclerosis",
    "Lichen simplex chronicus",
    "Hartnup disease",
    "Neuroleptic malignant syndrome",
    "Circumcision",
    "Postconcussion syndrome",
    "Thoracic spondylosis",
    "Mental retardation",
    "Neurosis",
    "Hypertension with pregnancy",
    "Alveolar proteinosis",
    "Myeloid maturation arrest",
    "Lymphocytic leukemia - chronic",
    "Hemangioma",
    "Giant cell tumor of bone",
    "Hepatitis exposure",
    "Fasciectomy",
    "Reye's syndrome",
    "Median neuropathy",
    "Arteriosclerosis",
    "Ulnar neuropathy",
    "Fanconi syndrome",
    "Hypothermia",
    "Cystic fibrosis",
    "Hematuria - gross",
    "Trochlear nerve palsy",
    "Colonic volvulus",
    "Colitis - ischemic",
    "Necrotizing enterocolitis",
    "Toxicity - digitalis",
    "Hyperlipoproteinemia (type V)",
    "Finger pain",
    "Finger sprain",
    "Tubular adenocarcinoma",
    "Adenoma - tubular",
    "Tonsillitis - acute",
    "Hyperplastic marrow",
    "Knee arthroplasty - total",
    "Anemia - myelophthisic",
    "Oophorectomy",
    "Vertebral burst fracture",
    "Histiocytoma - atypical fibrous",
    "Granuloma annulare",
    "Jejunostomy tube",
    "Verruca plantaris",
    "Lower leg/knee instability",
    "Shoulder instability",
    "Lymphangioma",
    "Hemangiopericytoma - malignant",
    "Acromegaly",
    "Erythema multiforme",
    "Psoriasis",
    "Lower gastrointestinal bleeding",
    "Thyroid cyst",
    "Alcohol abuse - continuous",
    "Vasovagal attack",
    "Pyloric obstruction",
    "Adenosquamous carcinoma",
    "Thyroglossal cyst",
    "Thyroid bruit",
    "Bladder stone",
    "Organic brain syndrome",
    "Nocturnal dyspnea",
    "Aortic valve abnormality",
    "Arteriovenous fistula",
    "Lateral meniscus tear",
    "Dyslexia",
    "Cartilage disorder",
    "Social phobia",
    "Nasolacrimal duct obstruction",
    "Radius fracture",
    "Throat cancer",
    "Paronychia",
    "Prurigo of pregnancy",
    "Failure to thrive",
    "Muscle strain",
    "Hyperlipoproteinemia (type IV)",
    "Serous cystadenocarcinoma",
    "Bronchopulmonary dysplasia",
    "Striae",
    "Hypertension - essential",
    "Meningismus",
    "Myoclonus",
    "Cervical vertebra fracture",
    "Creutzfeldt-Jakob disease",
    "Cervical dysplasia",
    "Melanoma - nodular",
    "Dysphagia",
    "Chondromalacia",
    "Alkaptonuria",
    "Below knee amputation",
    "Lower back pain",
    "Pyuria",
    "Linear immunoglobulin A dermatosis",
    "Intraepithelial lesion - squamous",
    "Pemphigus",
    "Cirrhosis - micronodular",
    "Dermatographism",
    "Hypothyroidism",
    "Infectious mononucleosis",
    "Epistaxis",
    "Gastrointestinal perforation",
    "Myocardial infarction",
    "Pheochromocytoma",
    "Lower leg injury",
    "Genitourinary surgery",
    "Sacroiliac sprain",
    "Weight loss",
    "Amyloid",
    "Melasma",
    "Glomerulonephritis - post-infectious",
    "Urinary stress incontinence - female",
    "Q fever",
    "Rabies",
    "Rubella syndrome",
    "Microcephaly",
    "Pruritus genitalia",
    "Laxative abuse",
    "Renal cyst - acquired",
    "Glomerulonephritis - membranous",
    "HELLP syndrome",
    "Hyperosmolality",
    "Autism",
    "Prinzmetal's angina",
    "Lymphangiectasis",
    "Elbow fracture",
    "Clavicle fracture",
    "Splenic rupture",
    "Bronchitis - acute",
    "Heart Attack",
    "Artery surgery",
    "Vulva cancer",
    "Diskectomy",
    "Thoracentesis",
    "Gastrectomy - subtotal",
    "Histocytosis",
    "Spermatocele"
]