# Generated by Django 4.1.12 on 2024-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="address",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="advanced_info",
            field=models.JSONField(null=True),
        ),
    ]
