# Generated by Django 4.1.12 on 2024-02-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0003_remove_trial_patient_profile_trial_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="location",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="principal_investigator",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Api.patientinfo",
            ),
        ),
        migrations.AddField(
            model_name="trial",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recruiting", "Recruiting"),
                    ("Completed", "Completed"),
                    ("Unkown", "Unknown"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
