# Generated by Django 4.1.12 on 2024-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0004_trial_contact_email_trial_distance_trial_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="nctid",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
