# Generated by Django 4.1.12 on 2024-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0005_trial_nctid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="condition",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
