version: '3.7'

services:

  sample:
    container_name: fe-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:42237
    environment:
      - CHOKIDAR_USEPOLLING=true