name: Api CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      TESTING: true
      USE_DEFAULT_DB: true
      FRONTEND_SERVICE_URL: http://testing
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/reach_backend/requirements.txt
    - name: Run lint
      run: |
        pylint --rcfile=src/backend/reach_backend/.pylintrc src/backend/reach_backend/Api
        black src/backend/reach_backend/Api
    - name: Run Tests
      run: |
        python src/backend/reach_backend/manage.py test Api.tests
